build:
  version: "1.0"
accounts:
  message: "Welcome to accounts related prod APIs "
  contactDetails:
    name: "John Bloggs - Prod Support"
    email: "john@tus.ie"
  onCallSupport:
    - (086) 555-1234
    - (087) 523-1345
