build:
  version: "1.0"
loans:
  message: "Welcome to loans related local APIs"
  contactDetails:
    name: "Katherine - Developer"
    email: "katherine.lee0356@gmail.com"
  onCallSupport:
    - (086) 555-1234
    - (087) 523-1345
    